DefaultDataDir: data
DatabaseFileName: data.db
RunMigrations: true
MigrationsPath: db/migrations
Auth:
  TokenSecret: "${TOKEN_SECRET}"
  TokenDuration: 24h
Setup:
  DefaultAdmin:
    Name: ${DEFAULT_ADMIN_NAME}
    Username: ${DEFAULT_ADMIN_USERNAME}
    Email: ${DEFAULT_ADMIN_EMAIL}
    Password: "${DEFAULT_ADMIN_PASSWORD}"
  TestUser:
    Name: ${TEST_USER_NAME}
    Username: ${TEST_USER_USERNAME}
    Email: ${TEST_USER_EMAIL}
    Password: "${TEST_USER_PASSWORD}"
RoleBindings:
  admin:
    - "admin"
  user:
    - "user"
    - "admin"
  public:
    - "public"
  DefaultRole: public
Menus:
  Rail:
    - Title: Dashboard
      Link: /app/dashboard
      Icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M13 3v6h8V3m-8 18h8V11h-8M3 21h8v-6H3m0-2h8V3H3z"/></svg>
      Roles: ["public", "user", "admin"]
    - Title: Settings
      MobileTitle: Settings
      Link: /app/settings
      Icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12 15.5A3.5 3.5 0 0 1 8.5 12A3.5 3.5 0 0 1 12 8.5a3.5 3.5 0 0 1 3.5 3.5a3.5 3.5 0 0 1-3.5 3.5m7.43-2.53c.04-.32.07-.64.07-.97s-.03-.66-.07-1l2.11-1.63c.19-.15.24-.42.12-.64l-2-3.46c-.12-.22-.39-.31-.61-.22l-2.49 1c-.52-.39-1.06-.73-1.69-.98l-.37-2.65A.506.506 0 0 0 14 2h-4c-.25 0-.46.18-.5.42l-.37 2.65c-.63.25-1.17.59-1.69.98l-2.49-1c-.22-.09-.49 0-.61.22l-2 3.46c-.13.22-.07.49.12.64L4.57 11c-.04.34-.07.67-.07 1s.03.65.07.97l-2.11 1.66c-.19.15-.25.42-.12.64l2 3.46c.12.22.39.3.61.22l2.49-1.01c.52.4 1.06.74 1.69.99l.37 2.65c.04.24.25.42.5.42h4c.25 0 .46-.18.5-.42l.37-2.65c.63-.26 1.17-.59 1.69-.99l2.49 1.01c.22.08.49 0 .61-.22l2-3.46c.12-.22.07-.49-.12-.64z"/></svg>
      Roles: ["user", "admin"]
      IsAtEnd: true
      SubItems:
        - Title: Account
          Lead: Update your account details
          Link: /app/settings/account
          Icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M6 17c0-2 4-3.1 6-3.1s6 1.1 6 3.1v1H6m9-9a3 3 0 0 1-3 3a3 3 0 0 1-3-3a3 3 0 0 1 3-3a3 3 0 0 1 3 3M3 5v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2"/></svg>
          Roles: ["user", "admin"]
        - Title: Billing
          Lead: Manage your billing details
          Link: /app/settings/billing
          Icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7 15h2c0 1.08 1.37 2 3 2s3-.92 3-2c0-1.1-1.04-1.5-3.24-2.03C9.64 12.44 7 11.78 7 9c0-1.79 1.47-3.31 3.5-3.82V3h3v2.18C15.53 5.69 17 7.21 17 9h-2c0-1.08-1.37-2-3-2s-3 .92-3 2c0 1.1 1.04 1.5 3.24 2.03C14.36 11.56 17 12.22 17 15c0 1.79-1.47 3.31-3.5 3.82V21h-3v-2.18C8.47 18.31 7 16.79 7 15"/></svg>
          Roles: ["user", "admin"]
        - Title: Switch Account
          Lead: Switch to another account
          Link: /app/settings/switch-account
          Icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="m21 9l-4-4v3h-7v2h7v3M7 11l-4 4l4 4v-3h7v-2H7z"/></svg>
          Roles: ["user", "admin"]
        - Title: Logout
          Link: /app/logout
          Icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="m17 7l-1.41 1.41L18.17 11H8v2h10.17l-2.58 2.58L17 17l5-5M4 5h8V3H4c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h8v-2H4z"/></svg>
          Roles: ["public", "user", "admin"]
          IsHtmx: false
          IsAtEnd: true
AllowedCountries:
  US: true # United States
  CA: true # Canada
  AU: true # Australia
  NZ: true # New Zealand
  AS: true # American Samoa
  GU: true # Guam
  MP: true # Northern Mariana Islands
  VI: true # U.S. Virgin Islands
  BS: true # Bahamas
  GB: true # United Kingdom
  IE: true # Ireland
  DE: true # Germany
  FR: true # France
  IT: true # Italy
  ES: true # Spain
  NL: true # Netherlands
  BE: true # Belgium
  DK: true # Denmark
  SE: true # Sweden
  FI: true # Finland
  NO: true # Norway
  CH: true # Switzerland
  AT: true # Austria
  LU: true # Luxembourg
  PT: true # Portugal
  IS: true # Iceland
  MT: true # Malta
